In [37]:
import pandas as pd
import numpy as np
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

# dfIso = pd.read_csv('Covid-19/owid-covid-data.csv')
dfVaccine = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')

In [38]:
print(dfVaccine.head())

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          1.0        1.0
1      AFG      Asia  Afghanistan  2020-02-25          1.0        0.0
2      AFG      Asia  Afghanistan  2020-02-26          1.0        0.0
3      AFG      Asia  Afghanistan  2020-02-27          1.0        0.0
4      AFG      Asia  Afghanistan  2020-02-28          1.0        0.0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...
1                 NaN           NaN         NaN                  NaN  ...
2                 NaN           NaN         NaN                  NaN  ...
3                 NaN           NaN         NaN                  NaN  ...
4                 NaN           NaN         NaN                  NaN  ...

   extreme_poverty  cardiovasc_death_rate  diabetes_prevalence  \
0              NaN                597.029                 9.59
1              NaN                597.029                 9.59
2              NaN                597.029                 9.59
3              NaN                597.029                 9.59
4              NaN                597.029                 9.59

   female_smokers  male_smokers  handwashing_facilities  \
0             NaN           NaN                  37.746
1             NaN           NaN                  37.746
2             NaN           NaN                  37.746
3             NaN           NaN                  37.746
4             NaN           NaN                  37.746

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         0.5            64.83                    0.511
1                         0.5            64.83                    0.511
2                         0.5            64.83                    0.511
3                         0.5            64.83                    0.511
4                         0.5            64.83                    0.511

   excess_mortality
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN

[5 rows x 62 columns]

In [39]:
for i in dfVaccine:
    print(i)

iso_code
continent
location
date
total_cases
new_cases
new_cases_smoothed
total_deaths
new_deaths
new_deaths_smoothed
total_cases_per_million
new_cases_per_million
new_cases_smoothed_per_million
total_deaths_per_million
new_deaths_per_million
new_deaths_smoothed_per_million
reproduction_rate
icu_patients
icu_patients_per_million
hosp_patients
hosp_patients_per_million
weekly_icu_admissions
weekly_icu_admissions_per_million
weekly_hosp_admissions
weekly_hosp_admissions_per_million
new_tests
total_tests
total_tests_per_thousand
new_tests_per_thousand
new_tests_smoothed
new_tests_smoothed_per_thousand
positive_rate
tests_per_case
tests_units
total_vaccinations
people_vaccinated
people_fully_vaccinated
total_boosters
new_vaccinations
new_vaccinations_smoothed
total_vaccinations_per_hundred
people_vaccinated_per_hundred
people_fully_vaccinated_per_hundred
total_boosters_per_hundred
new_vaccinations_smoothed_per_million
stringency_index
population
population_density
median_age
aged_65_older
aged_70_older
gdp_per_capita
extreme_poverty
cardiovasc_death_rate
diabetes_prevalence
female_smokers
male_smokers
handwashing_facilities
hospital_beds_per_thousand
life_expectancy
human_development_index
excess_mortality

In [40]:
dfVaccine.to_csv('data20Aug2021.csv')

In [41]:
taken_field = [
    'iso_code',
    'continent',
    'location',
    'date',
    'total_cases',
    'new_cases',
    'total_deaths',
    'new_deaths',
    'positive_rate',
    'total_vaccinations',
    'people_vaccinated',
    'people_fully_vaccinated',
    'total_boosters',
    'new_vaccinations',
    'population',
    'median_age',
    'aged_65_older',
    'aged_70_older',
]

dfC19 = dfVaccine[taken_field].copy()
print(dfC19.head())

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          1.0        1.0
1      AFG      Asia  Afghanistan  2020-02-25          1.0        0.0
2      AFG      Asia  Afghanistan  2020-02-26          1.0        0.0
3      AFG      Asia  Afghanistan  2020-02-27          1.0        0.0
4      AFG      Asia  Afghanistan  2020-02-28          1.0        0.0

   total_deaths  new_deaths  positive_rate  total_vaccinations  \
0           NaN         NaN            NaN                 NaN
1           NaN         NaN            NaN                 NaN
2           NaN         NaN            NaN                 NaN
3           NaN         NaN            NaN                 NaN
4           NaN         NaN            NaN                 NaN

   people_vaccinated  people_fully_vaccinated  total_boosters  \
0                NaN                      NaN             NaN
1                NaN                      NaN             NaN
2                NaN                      NaN             NaN
3                NaN                      NaN             NaN
4                NaN                      NaN             NaN

   new_vaccinations  population  median_age  aged_65_older  aged_70_older
0               NaN  38928341.0        18.6          2.581          1.337
1               NaN  38928341.0        18.6          2.581          1.337
2               NaN  38928341.0        18.6          2.581          1.337
3               NaN  38928341.0        18.6          2.581          1.337
4               NaN  38928341.0        18.6          2.581          1.337

In [42]:
dfC19 = dfC19.fillna(0)

In [48]:
dfC19['continent'] = dfC19['continent'].replace(0,'World')
check = dfC19.loc[dfC19['continent'] == 'World']
print(check)

        iso_code continent location        date  total_cases  new_cases  \
543     OWID_AFR     World   Africa  2020-02-13          0.0        0.0
544     OWID_AFR     World   Africa  2020-02-14          1.0        1.0
545     OWID_AFR     World   Africa  2020-02-15          1.0        0.0
546     OWID_AFR     World   Africa  2020-02-16          1.0        0.0
547     OWID_AFR     World   Africa  2020-02-17          1.0        0.0
...          ...       ...      ...         ...          ...        ...
109131  OWID_WRL     World    World  2021-08-15  207267360.0   459851.0
109132  OWID_WRL     World    World  2021-08-16  207937090.0   669730.0
109133  OWID_WRL     World    World  2021-08-17  208595814.0   658724.0
109134  OWID_WRL     World    World  2021-08-18  209303622.0   707808.0
109135  OWID_WRL     World    World  2021-08-19  209963660.0   660038.0

        total_deaths  new_deaths  positive_rate  total_vaccinations  \
543              0.0         0.0            0.0        0.000000e+00
544              0.0         0.0            0.0        0.000000e+00
545              0.0         0.0            0.0        0.000000e+00
546              0.0         0.0            0.0        0.000000e+00
547              0.0         0.0            0.0        0.000000e+00
...              ...         ...            ...                 ...
109131     4361973.0      7215.0            0.0        4.725888e+09
109132     4371437.0      9464.0            0.0        4.768237e+09
109133     4382152.0     10715.0            0.0        4.806597e+09
109134     4392967.0     10815.0            0.0        4.837764e+09
109135     4403038.0     10071.0            0.0        0.000000e+00

        people_vaccinated  people_fully_vaccinated  total_boosters  \
543          0.000000e+00             0.000000e+00             0.0
544          0.000000e+00             0.000000e+00             0.0
545          0.000000e+00             0.000000e+00             0.0
546          0.000000e+00             0.000000e+00             0.0
547          0.000000e+00             0.000000e+00             0.0
...                   ...                      ...             ...
109131       2.447981e+09             1.841640e+09       8274658.0
109132       2.467163e+09             1.852458e+09       8589539.0
109133       2.480995e+09             1.864319e+09       8959843.0
109134       2.491591e+09             1.871760e+09       9387485.0
109135       0.000000e+00             0.000000e+00             0.0

        new_vaccinations    population  median_age  aged_65_older  \
543                  0.0  1.340598e+09         0.0          0.000
544                  0.0  1.340598e+09         0.0          0.000
545                  0.0  1.340598e+09         0.0          0.000
546                  0.0  1.340598e+09         0.0          0.000
547                  0.0  1.340598e+09         0.0          0.000
...                  ...           ...         ...            ...
109131        26362976.0  7.794799e+09        30.9          8.696
109132        42348986.0  7.794799e+09        30.9          8.696
109133        38359822.0  7.794799e+09        30.9          8.696
109134        31166794.0  7.794799e+09        30.9          8.696
109135               0.0  7.794799e+09        30.9          8.696

        aged_70_older
543             0.000
544             0.000
545             0.000
546             0.000
547             0.000
...               ...
109131          5.355
109132          5.355
109133          5.355
109134          5.355
109135          5.355

[5110 rows x 18 columns]

In [25]:
indo = dfC19.loc[dfC19['location'] == 'Indonesia']
indo.head()

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,positive_rate,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,population,median_age,aged_65_older,aged_70_older
46187,IDN,Asia,Indonesia,2020-03-02,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273523621.0,29.3,5.319,3.053
46188,IDN,Asia,Indonesia,2020-03-03,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273523621.0,29.3,5.319,3.053
46189,IDN,Asia,Indonesia,2020-03-04,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273523621.0,29.3,5.319,3.053
46190,IDN,Asia,Indonesia,2020-03-05,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273523621.0,29.3,5.319,3.053
46191,IDN,Asia,Indonesia,2020-03-06,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273523621.0,29.3,5.319,3.053

In [28]:
countries_list = dfC19[['iso_code','location']].copy()
countries_list = countries_list.drop_duplicates()
countries_list.head(10)

      iso_code             location
0          AFG          Afghanistan
542   OWID_AFR               Africa
1095       ALB              Albania
1636       DZA              Algeria
2177       AND              Andorra
2712       AGO               Angola
3229       AIA             Anguilla
3413       ATG  Antigua and Barbuda
3937       ARG            Argentina
4533       ARM              Armenia